### PR TITLE
feature: add messageTimestamp to MessageMetaData and implement a Comp…

### LINKED ISSUE #44: Support sorting of messages within a batch by messageTimestamp
### Scenario

* Library version: 1.1.0
* Description of your use case: We need to make sure that messages with the same batch key are processed exactly in the order they arrive. This means we need a `CorrelationMessageComparator` that sorts by `messageTimestamp`.

### Current Behaviour

The `messageTimestamp` is already part of the `MessageMetaDataSnippet` but not of `MessageMetaData`. Thus, in the comparator, we don't have the data we need to sort by it.

### Wanted Behaviour

`messageTimestamp` is available in `MessageMetaData` and can be used to sort `CorrelationMessage`s by it. Bonus: There's a default implementation of a `CorrelationMessageComparator` that sorts by `messageTimestamp`.

### PR DESCRIPTION
**Pull request by lbilger**
…arator that sorts by it.

Fixes #44

Note: the approach of mapping `messageTimestamp` to `inserted` is subject to discussion. It keeps things simple because it doesn't require an extra field in `MessageEntity`, but one could argue that it is not completely clean because the `messageTimestamp` is not necessarily the time the message was inserted into the database. @zambrovski I would like to know your opinion regarding this choice.

### CODE REVIEW

**Comment by zambrovski** [comment]
Hi @lbilger.
I believe this was exactly the idea. 
Let me sort this things out and re-think your implementation.

Step 1: Kafka extractore reads message timestamp header and put that int a generic Header Map using "X-CORRELATE-Timestamp" key. I believe if it is not set, it should default to Instant.now() on receive.

Step 2: The metadata extractor chain uses `HeaderMessageMetaDataSnippetExtractor` to extract the metadata snipppet.

Step 3: If nothing else is configured it will create the MessageMetadata from the snippets and use the provided timestamp as message timestamp.

Step 4: (your change) use the timestamp as insertedDate, or fallback to Instant.now(). 

Step 5: the instant is used for sorting during retrieval.

Sounds reasonable...


I would just introduce a minor change, where the default Instant.now() is set.

I also added a test to make sure, reduce works as desired.

**Comment by lbilger** [comment]
Hi Simon, I can't see any comment on Issue #44 (I guess that's what you meant). Also, you mentioned you added a test, but I can't see that commit either.

**Comment by zambrovski** [comment]
@lbilger please read this thread: https://github.com/holunda-io/camunda-bpm-correlate/pull/45#issuecomment-1579049510

**Comment by lbilger** [comment]
Sorry if I'm a bit slow here, but where do you think the default should be set?

**Review by zambrovski — APPROVED** [review]

**Comment by zambrovski** [comment]
I changed the default setting on your branch, and will approve it now. Please just check my change before merging...

**Comment by lbilger** [comment]
Ah, now I see what you meant. I assume the version updates were accidentally pushed to this branch instead of develop, but that shouldn't hurt. Merging now.

**Pull request merged**
